spring:
  datasource:
    url: jdbc:mysql://localhost:3306/university
    username : root
    password :
  jpa:
    database: mysql
  appication:
    name: student-app
server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080/
  realm : Infybuzz
  resource : students-app
  credentials:
    secret: 8jnbwf8cRFIpdS72bWOijHFR28OhdtNi
  principal-attribute: preferred_username


#eureka:
#  instance:
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#logging:
#  level:
#   com.infybuzz: DEBUG
#
#
#{
#  "realm": "Infybuzz",
#  "auth-server-url": "http://localhost:8080/",
#  "ssl-required": "external",
#  "resource": "students-app",
#  "credentials": {
#    "secret": "8jnbwf8cRFIpdS72bWOijHFR28OhdtNi"
#  },
#  "confidential-port": 0
#}

#spring.datasource.url=jdbc:mysql://localhost:3306/university
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.database=mysql
#
#server.port=8081
#
#keycloak.auth-server-url=http://localhost:8080/auth
#keycloak.realm=Infybuzz
#keycloak.resource=student-app
#keycloak.credentials.secret=8b925ef6-4118-4ca1-8b44-f54357e3f67a


#spring.datasource.url=jdbc:mysql://localhost:3306/university
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.database=mysql
#
#server.port=8081
#
#keycloak.auth-server-url=http://localhost:8080/auth
#keycloak.realm=Infybuzz
#keycloak.resource=student-app
#keycloak.credentials.secret=8b925ef6-4118-4ca1-8b44-f54357e3f67a
#
#keycloak.principal-attribute=preferred_username
